#!/bin/bash

set -o errexit
set -o nounset

source "$(dirname ${BASH_SOURCE})/config.source"
source "$(dirname ${BASH_SOURCE})/errors.source"
source "$(dirname ${BASH_SOURCE})/tsi-handle-command.source"
source "$(dirname ${BASH_SOURCE})/create/tsi-create.source"
source "$(dirname ${BASH_SOURCE})/create/tsi-doc.source"
source "$(dirname ${BASH_SOURCE})/create/tsi-tree.source"
source "$(dirname ${BASH_SOURCE})/create/node/tsi-node.source"
source "$(dirname ${BASH_SOURCE})/create/node/tsi-node-std.source"
source "$(dirname ${BASH_SOURCE})/create/node/tsi-node-ref.source"
source "$(dirname ${BASH_SOURCE})/create/node/tsi-node-ref-dec.source"
source "$(dirname ${BASH_SOURCE})/create/node/tsi-node-ref-def.source"
source "$(dirname ${BASH_SOURCE})/create/attr/tsi-attr.source"
source "$(dirname ${BASH_SOURCE})/create/attr/tsi-attr-std.source"
source "$(dirname ${BASH_SOURCE})/create/attr/tsi-attr-ref.source"
source "$(dirname ${BASH_SOURCE})/create/attr/tsi-attr-ref-dec.source"
source "$(dirname ${BASH_SOURCE})/create/attr/tsi-attr-ref-def.source"
source "$(dirname ${BASH_SOURCE})/utils.source"

[[ "${#}" == "0" ]] \
    && tsi_handle_too_little_pos_params_err

while [[ "${#}" -gt "0" ]]
do
    case "${1}" in
        "--version")
            [[ "${#}" -gt "1" ]] \
                && tsi_handle_too_many_pos_params_err

            tsi_display_app_version
            shift "1"
            ;;
        *)
            tsi_handle_command "${@}"
            shift "${#}"
            ;;
    esac
done