#!/bin/bash

set -o nounset

source "$(dirname ${BASH_SOURCE})/../test-utils.source" \
    || exit "1"

testing_exit_status="0"

echo "Started integration testing..."

test_cases_dir_path="$(dirname ${BASH_SOURCE})/integration-test-cases/"
test_cases="$(find ${test_cases_dir_path} -type f)"

for test_cases_file_path in ${test_cases}
do
    echo "Testing ${test_cases_file_path}"
    
    source "${test_cases_file_path}"
    testing_exit_status="${?}"

    if [[ "${testing_exit_status}" != "0" ]]
    then exit "${testing_exit_status}"
    fi
done

echo "Integration testing done: all tests passed"