#!/bin/bash

set -o errexit
set -o nounset

source "$(dirname ${BASH_SOURCE})/config.source"
source "$(dirname ${BASH_SOURCE})/errors.source"
source "$(dirname ${BASH_SOURCE})/tsi-handle-command.source"
source "$(dirname ${BASH_SOURCE})/tsi-create.source"
source "$(dirname ${BASH_SOURCE})/tsi-doc.source"
source "$(dirname ${BASH_SOURCE})/tsi-tree.source"
source "$(dirname ${BASH_SOURCE})/utils.source"

command -v "echo" > /dev/null \
    || exit "1"

[[ "${#}" == "0" ]] \
    && tsi_handle_no_param_err

while [[ "${#}" -gt "0" ]]
do
    case "${1}" in
        "--version")
            [[ "${#}" -gt "1" ]] \
                && tsi_handle_too_many_params_err
            echo "Not implemented"
            # display_app_version
            shift "1"
            ;;
        *)
            tsi_handle_command "${@}"
            shift "${#}"
            ;;
    esac
done