#!/bin/bash

set -o nounset

source "$(dirname ${BASH_SOURCE})/../test-utils.source" \
    || exit "1"

source "$(dirname ${BASH_SOURCE})/../../src/config.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/errors.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/tsi-handle-command.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/tsi-create.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/tsi-doc.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/tsi-tree.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/node/tsi-node.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/node/tsi-node-std.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/node/tsi-node-ref.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/node/tsi-node-ref-dec.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/node/tsi-node-ref-def.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/attr/tsi-attr.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/attr/tsi-attr-std.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/attr/tsi-attr-ref.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/attr/tsi-attr-ref-dec.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/create/attr/tsi-attr-ref-def.source" \
    || exit "1"
source "$(dirname ${BASH_SOURCE})/../../src/utils.source" \
    || exit "1"

testing_exit_status="0"

echo "Started unit testing..."

test_cases_dir_path="$(dirname ${BASH_SOURCE})/unit-test-cases/"
test_cases="$(find ${test_cases_dir_path} -type f)"

for test_cases_file_path in ${test_cases}
do
    echo "Testing ${test_cases_file_path}..."
    
    source "${test_cases_file_path}"
    testing_exit_status="${?}"

    if [[ "${testing_exit_status}" != "0" ]]
    then exit "${testing_exit_status}"
    fi
done

echo "Unit testing done: all tests passed"